services:
  - type: web
    name: studypilot-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SUPABASE_DB_URL
        value: jdbc:postgresql://aws-0-eu-west-2.pooler.supabase.com:5432/postgres
      - key: SUPABASE_DB_USER
        value: postgres.oyyhqjpemqltsqjlxyqn
      - key: SUPABASE_DB_PASSWORD
        fromVariable: SUPABASE_DB_PASSWORD
      - key: SUPABASE_URL
        value: ${SUPABASE_URL}
      - key: SUPABASE_KEY
        value: ${SUPABASE_KEY}
      - key: SUPABASE_STORAGE_BUCKET
        value: syllabi